#!/bin/bash

#   deploy-branchster  -  Make the ipa, manifest, and web page for Branchster.
#
#   E.B. Smith  February 2017.

set -eu -o pipefail
scriptname="$(basename "$0")"
scriptpath="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$scriptpath"/..


baseurl="https://shimmering.blue/ios/branchster"
stagingpath=./Staging-Branchster
deployapp=BranchMonsterFactory

source ./Tools/color-source

function showErrorOnExit() {
    printf "${textRed}"
    printf " -------------------------------------------------------------------\n"
    printf "                            Deploy failed.\n"
    printf " -------------------------------------------------------------------"
    printf "${textNormal}\n"
}
trap "showErrorOnExit" EXIT


printf "${textBlue}>>> Deploying: `pwd`${textNormal}\n"

# ./Tools/ipa-install-cocoapods
./Tools/ipa-make-archive

printf "${textBlue}>>> Making manifest...${textNormal}\n"
./Tools/ipa-make-manifest -u "${baseurl}" "$stagingpath"/"$deployapp".ipa > "$stagingpath"/"$deployapp".plist

printf "${textBlue}>>> Making webpage...${textNormal}\n"
./Tools/ipa-make-webpage  -u "${baseurl}" "$stagingpath"/"$deployapp".ipa > "$stagingpath"/index.html

printf "${textBlue}>>> Uploading...${textNormal}\n"
./Tools/deploy-upload-rsync

trap - EXIT
printf "${textBlue}"
printf ">>> $deployapp deployed.${textNormal}\n"
