#!/bin/bash

set -eu -o pipefail
scriptname="$(basename "$0")"
scriptpath="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

deployapp=BranchMonsterFactory
deployhost="blitzhere@blitzhere.com"
baseurl="https://blitzhere.com/ios/blitz-labs"
deploypath="/home/blitzhere/www/ios/blitz-labs"
stagingpath="${scriptpath}"/Staging-Branchster


if [[ ${CLICOLOR:0} == 1 && -t 1 ]]; then
    textBold="\e[1m"
    textBlue="\e[94m"
    textDarkBlue="\e[1m\e[34m"
    textYellow="\e[93m"
    textRed="\e[31m"
    textNormal="\e[0m"
    textDim="\e[2m"
else
    textBold=""
    textBlue=""
    textDarkBlue=""
    textYellow=""
    textRed=""
    textNormal=""
    textDim=""
fi

function showErrorOnExit() {
    printf "${textRed}"
    printf "[build-all] -------------------------------------------------------------------\n"
    printf "[build-all]                             Deploy failed.\n"
    printf "[build-all] -------------------------------------------------------------------"
    printf "${textNormal}\n"
}
trap "showErrorOnExit" EXIT


cd "$stagingpath"
echo ">>> Deploying: `pwd`"
echo ">>>        To: $deployhost:$deploypath"
make-manifest -u "${baseurl}" "${deployapp}".ipa > "${deployapp}".plist
make-webpage  -u "${baseurl}" "${deployapp}".ipa > index.html

ssh "$deployhost" mkdir -p "$deploypath"
rsync -aP "$stagingpath"/* "$deployhost":"$deploypath"
ssh "$deployhost" chmod -R 755 "$deploypath"

trap - EXIT
printf "${textBlue}"
printf ">>> $deployapp deployed to $deployhost.${textNormal}\n"
