#!/bin/bash

#   deploy-branchster  -  Make the ipa, manifest, and web page for Branchster.
#
#   E.B. Smith  February 2017.

set -eu -o pipefail
scriptname="$(basename "$0")"
scriptpath="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$scriptpath"/..
pwd

deployapp=BranchMonsterFactory
deployhost="shimmering@shimmering.blue"
baseurl="https://shimmering.blue/ios/branchster"
deploypath="/home/shimmering/www/blue.shimmering/ios/branchster"
stagingpath=./Staging-Branchster


if [[ ${CLICOLOR:0} == 1 && -t 1 ]]; then
    textBold="\e[1m"
    textBlue="\e[94m"
    textDarkBlue="\e[1m\e[34m"
    textYellow="\e[93m"
    textRed="\e[31m"
    textNormal="\e[0m"
    textDim="\e[2m"
else
    textBold=""
    textBlue=""
    textDarkBlue=""
    textYellow=""
    textRed=""
    textNormal=""
    textDim=""
fi

function showErrorOnExit() {
    printf "${textRed}"
    printf " -------------------------------------------------------------------\n"
    printf "                            Deploy failed.\n"
    printf " -------------------------------------------------------------------"
    printf "${textNormal}\n"
}
trap "showErrorOnExit" EXIT


echo ">>> Deploying: `pwd`"
echo ">>>        To: $deployhost:$deploypath"

# ./Tools/ipa-make-archive

echo ">>> Making manifest..."
./Tools/ipa-make-manifest -u "${baseurl}" "$stagingpath"/"$deployapp".ipa > "$stagingpath"/"$deployapp".plist

echo ">>> Making webpage..."
./Tools/ipa-make-webpage  -u "${baseurl}" "$stagingpath"/"$deployapp".ipa > "$stagingpath"/index.html

echo ">>> Uploading archive..."
ssh "$deployhost" mkdir -p "$deploypath"
rsync -aP "$stagingpath"/* "$deployhost":"$deploypath"
ssh "$deployhost" chmod -R 755 "$deploypath"

trap - EXIT
printf "${textBlue}"
printf ">>> $deployapp deployed to $deployhost.${textNormal}\n"
