#!/bin/bash

#   ipa-tool  -  A front-end script for the iPhone ipa app file distribution tools.
#
#   E.B. Smith  -  November 2014.


#set -vx
set -eu -o pipefail
scriptname="ipa-tool"
scriptpath="${BASH_SOURCE[0]}"
while [ -L "${scriptpath}" ]; do
    scriptpath=$(readlink "${scriptpath}")
    done
scriptpath=$(cd "$(dirname "${scriptpath}")" && pwd)


function usage() {
cat <<USAGE

Usage: ipa-tool  <command>  <options>

ipa-tool commands:

help   add-id   publish-invite   publish-update   make-manifest   add-timestamp

USAGE
}


if (( ${#@} == 0 )); then
    usage
    exit 0
    fi

bHelp=false
command="$1"
commandpath="${scriptpath}"/ipa-tools/ipa-$command
if [ -t 1 ] || ${ipaTerminalOutput-false}; then
    export ipaTerminalOutput=true
else
    export ipaTerminalOutput=false
    fi

if [[ $command == "help" ]]; then
    shift
    if (( ${#@} == 0 )); then
        usage
        exit 0
        fi
    bHelp=true
    command=$1
    commandpath="${scriptpath}"/ipa-tools/ipa-$command
    fi

#echo $commandpath

if [ ! -f "${commandpath}" ]; then
    echo ">>> Error: unknown command '$command'." >&2
    usage
    exit 1
    fi

if $bHelp; then
    "${commandpath}" -h
else
    "${commandpath}" ${@:2}
    fi
