#!/bin/bash
# February 2017, Edward Smith
# Script line:
# ./Tools/ipa-add-timestamp
# Dependency line:
# $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
set -euo pipefail
if (( $# == 1 ))
then
    target="$1"
else
    target="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
fi
echo "Updating date '`date`' in '$target'."
(/usr/libexec/PlistBuddy -c "delete :ZBuildInfoDate" "${target}" || true)
 /usr/libexec/PlistBuddy -c "add :ZBuildInfoDate date `date`" "${target}"
